version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    working_dir: /var/www/html
 
    # ホストユーザーのUID/GIDを適用
    user: "${UID}:${GID}" 

    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # Laravel アプリケーションキー
      - APP_KEY=${APP_KEY}
      # メール設定
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      # Laravelコンテナの環境変数にUID/GIDを渡す（userディレクティブ利用のため）
      - PUID=${UID} 
      - PGID=${GID}
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: laravel_nginx
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

# phpMyAdminを追加
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fishing_circle_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: